### ISSUE TITLE
Better flathub profile pic

### ISSUE THREAD

**Issue by superdreamkilla** [flathub/io.sourceforge.Pixelitor#1]
lol, The profile pic for Pixelitor is actually my Desktop and it was "kind of crude".

I don't mind using my desktop but I'd prefer to make the image less amateurish. BTW Pixelitor 4.24 is going to be released very soon. So it's not an issue at all that the screenshot is a newer release.

![image](https://user-images.githubusercontent.com/61440491/104671299-6f48d900-56d5-11eb-92c5-60f6b27841e5.png)

![image](https://user-images.githubusercontent.com/61440491/104671368-90112e80-56d5-11eb-91c9-3bda60c2ef12.png)

![image](https://user-images.githubusercontent.com/61440491/104671398-a323fe80-56d5-11eb-92d6-63f911359955.png)

![image](https://user-images.githubusercontent.com/61440491/104671553-f39b5c00-56d5-11eb-8021-860223bc4660.png)

![image](https://user-images.githubusercontent.com/61440491/104671691-32c9ad00-56d6-11eb-995f-858de89078e9.png)

![image](https://user-images.githubusercontent.com/61440491/104671793-673d6900-56d6-11eb-8e71-b2074b26c752.png)

![image](https://user-images.githubusercontent.com/61440491/104672394-a28c6780-56d7-11eb-9a41-a92968655740.png)

![image](https://user-images.githubusercontent.com/61440491/104672427-b041ed00-56d7-11eb-8d87-9b6d2acee5ab.png)

![image](https://user-images.githubusercontent.com/61440491/104672458-bc2daf00-56d7-11eb-9ebd-a7d1287f4748.png)

![image](https://user-images.githubusercontent.com/61440491/104672622-06169500-56d8-11eb-953f-fc61719ae30e.png)

**Comment by lbalazscs** [comment]
Oh, I didn't even realize that Pixelitor is already on flathub... but great (I'm still planning to understand how all this works). I will link to it from the homepage (within a day).

I like these screenshots, especially the purplewhirl, I will also use that one on the homepage, if you don't mind. And in general, I agree that these images are better suited for flathub. Actually my screenshots on sourceforge were taken on Windows, and therefore they are totally inappropriate :)

**Comment by superdreamkilla** [comment]
Go ahead and use any of these for the home page and flathub. I would prefer you do.  The font used in the first one is an open source font "Galindo".

**Comment by lbalazscs** [comment]
I updated the homepage and the metainfo image here. In the metainfo I linked the images directly from GitHub, I hope that's OK. I don't know how the updating of the actual flathub page can be triggered.

**Comment by superdreamkilla** [comment]
Ask some of the flathub guys. I dunno either.

**Comment by lbalazscs** [comment]
The flathub guys are watchers for this repository, they should be notified of any discussions. My comments were therefore directed towards a general audience, not towards you specifically... 

Also, it's possible that there is some automatic process that periodically updates the webpages. So let's wait and hope :)

**Comment by lbalazscs** [comment]
The pages were updated after all (without me doing anything...), so I guess this issue can be closed.
